[package]
name = "theseus_xargo"
version = "0.1.0"
authors = [
    "Kevin Boos <kevinaboos@gmail.com>",
]
description = "A wrapper around cargo that cross-compiles Theseus components, handles out-of-tree builds based on a set of pre-built Theseus crate .rlibs,  and performs special partially-static linking procedures."

[dependencies]
getopts = "0.2"
walkdir = "2.2.7"
regex = "1.4.2"
itertools = "0.9.0"