[package]
name = "libtheseus"
version = "0.1.0"
description = "The application-facing 'library' that exposes Theseus OS features, similar to a standard library."
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
build = "../build.rs"
links = "serial_port"

[dependencies]
rlibc = "1.0.0"
# getopts = "0.2.21"

[dependencies.serial_port]
path = "../kernel/serial_port"

# [dependencies.panic_entry]
# path = "../kernel/panic_entry"

# [dependencies.heap]
# path = "../kernel/heap"


# [dependencies.terminal_print]
# path = "../kernel/terminal_print"

# [lib]
# crate-type = [ "rlib", "staticlib" ]
# crate-type = ["rlib", "staticlib", "dylib"]
# crate-type = ["staticlib"]
# crate-type = ["dylib"]
# crate-type = ["cdylib"]

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
incremental = false